name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
        type: [ "Debug", "Release" ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.type }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.type }}

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest --extra-verbose -C ${{ matrix.type }}
